name: Ping Website

on:
  schedule:
    - cron: "*/4 * * * *"   # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping cricketdata site
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://spiderrepo.onrender.com/)
          echo "HTTP status: $STATUS"

          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Website returned status $STATUS"
            exit 1
          else
            echo "✅ Website is up and healthy"
          fi
